# Generated by Django 3.1.2 on 2021-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chainstay', models.DecimalField(decimal_places=1, max_digits=4)),
                ('seat_tube_angle', models.DecimalField(decimal_places=1, max_digits=4)),
                ('head_tube_angle', models.DecimalField(decimal_places=1, max_digits=4)),
                ('frame_pic', models.ImageField(upload_to='frame_pics')),
                ('link', models.CharField(max_length=150)),
            ],
        ),
    ]
