# Generated by Django 3.1.2 on 2021-03-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
