# Generated by Django 3.1.2 on 2021-03-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesearch', '0002_frame_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='frame',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='frame',
            name='size',
            field=models.ManyToManyField(to='framesearch.FrameSize'),
        ),
    ]
