# Generated by Django 3.1.2 on 2021-03-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesearch', '0003_auto_20210307_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='chainstay_processed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='head_tube_processed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='seat_tube_processed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
