# Generated by Django 3.1.2 on 2021-03-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesearch', '0007_auto_20210310_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='chainstay',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='frame',
            name='head_tube_angle',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='frame',
            name='seat_tube_angle',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
