# Generated by Django 3.1.2 on 2021-03-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesearch', '0008_auto_20210310_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='discipline_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
