# Generated by Django 3.1.2 on 2021-03-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesearch', '0010_frame_suitability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='suitability',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
